sudo: required
services:
  - docker

before_install:
  - docker build -t onechaiev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true onechaiev/react-test npm test 

after_success:
  - docker build -t onechaiev/multi-client ./client
  - docker build -t onechaiev/multi-nginx ./nginx
  - docker build -t onechaiev/multi-server ./server
  - docker build -t onechaiev/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push onechaiev/multi-client
  - docker push onechaiev/multi-nginx
  - docker push onechaiev/multi-server
  - docker push onechaiev/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-850109877226
  bucket_path: docker-multi
  on:
    master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY